### ISSUE TITLE
v2.1.0 release plan

### ISSUE THREAD

**Issue by bollwyvl** [conda-incubator/setup-miniconda#106]
Stuff is starting to pile up! 

- bug fixes

- features
  - [x] #89 performance
  - [ ] #75 micromamba
  - [x] #76 miniforge
- chores
  - [x] update README
  - [x] update CHANGELOG
  - [ ] tag
  - [ ] move `v2` tag
  - [ ] update release process with lessons learned

**Comment by goanpeca** [comment]
Hi @bollwyvl thanks for openning this.

>bug fixes (maybe we want to cut a bugfix 2.0.1 with what's already in the can?)

Yes, I created a separate milestone, will move the issues and prepare a new cut with the bugfixes.

Also left some comments on the other PRs on the refactor.

**Comment by ma-sadeghi** [comment]
Hi! Is there an ETA for v2.1?

**Comment by xhochy** [comment]
Can we reduce the scope down to include the miniforge changes? They are working quite well in some repos and thus it would be nice to have them in a tagged release.

**Comment by hadim** [comment]
I agree. Currently working on `master` and it works fine. I would love to be able to pin to a tagged version of the action.

**Comment by goanpeca** [comment]
So I forgot I had committed to make this release like a week ago. Just to double check with @conda-incubator/setup-miniconda-team any comments/suggestions before I go ahead to make the release?

**Comment by bollwyvl** [comment]
:shipit:

**Comment by jaimergp** [comment]
🚀 Go for it!

**Comment by ktbarrett** [comment]
Bump...

**Comment by bollwyvl** [comment]
Punched off a couple of the items above... @goanpeca are you going to be able to drop 2.1 in the next few days?

**Comment by goanpeca** [comment]
Released @bollwyvl !

**Comment by blink1073** [comment]
:tada:

**Comment by bollwyvl** [comment]
Hooray!
