### ISSUE TITLE
Override environment.yaml name

### ISSUE THREAD

**Issue by JulioV** [conda-incubator/setup-miniconda#122]
Is there a way to override the name of the environment created from an `environment.yaml` file (a.k.a. the `--name` flag)?

BTW, thanks for your work, it saved me a lot fo time!

**Comment by goanpeca** [comment]
Hi @JulioV, thanks for your suggestion and your kind words :)

>Is there a way to override the name of the environment created from an environment.yaml file (a.k.a. the --name flag)?

Well could you describe a bit more what you are trying to accomplish?

**Comment by JulioV** [comment]
Our conda environment is named like this `projectYYYYMM`, so every time the `name` attributes changes in our `environment.yaml` file I need to change `activate-environment` in your action. Is there a way to pass an environment name to your action, so that it does not have to match the `name` attribute in the file?

**Comment by goanpeca** [comment]
>Is there a way to pass an environment name to your action, so that it does not have to match the name attribute in the file?

`test-environment` serves this purpose, but I think they need to be the same, or it needs to be missing from he env yaml, so I don't think we support you use case at the moment.

**Comment by JulioV** [comment]
Oh OK, can I transform this issue into a future request? :)

**Comment by jaimergp** [comment]
You could patch the `environment.yml` file in a previous step with `sed` and friends. Ugly but would work for now :)

**Comment by JulioV** [comment]
@jaimergp, thanks, that's what I thought. For anyone seeing this in the future I did  ` sed -i "" "s/name:.*/name:my_new_name/g" environment.yml`

**Comment by bollwyvl** [comment]
So do you want your environment to get created with the name:
- `test`
- `projectyyymmdd` 
- or some other name specified in your file (other than `base` or `root`)

More broadly: what should the order of preference be (not _your_ preference for this use case, but _least surprising_ for the most people? Practically, I think over on #127 i'm at a place where I can fix this, if it hasn't already done so.

My spitballing hierarchy, from most- to least-explicit:
- no name in env, name in workflow:  whatever was in workflow (if not `base` or `root`)
- name in env, name in workflow: whatever was in workflow (if not `base` or `root`)
- name in env, no name in workflow: ????
  - > i think it's `test` right now, and not sure if anybody likes that, but also don't know if we can change it, now
- no name in env, no name in workflow: `test`

Some thoughts for the future:
- explicit envs already don't have a name, so there's nothing to fall back on
- if multiple env files are supported, what then?

**Comment by bollwyvl** [comment]
Concretely from #127: the YAML installer (in [env/yaml.ts](https://github.com/conda-incubator/setup-miniconda/pull/127/files#diff-c987e7706a38e59356d17e72f4338710f538489255a968ca42a40d4bb01870ddR107)) _doesn't even look_ at the `name` specified in the enviroment file... but it could, if we agree on that logic above. Though likely, we should just resolve it on a separate PR, adding new tests, etc.

**Comment by goanpeca** [comment]
Hi @bollwyvl, let's keep the effort of fixing other bugs separate from the refactoring work :)

**Comment by bollwyvl** [comment]
As of `master`, this is probably fixed:

https://github.com/conda-incubator/setup-miniconda/blob/master/src/env/yaml.ts#L122

**Comment by goanpeca** [comment]
Thanks @bollwyvl closing for now
