### ISSUE TITLE
docs: would be helpful to warn that a login bash shell is needed

### ISSUE THREAD

**Issue by magland** [conda-incubator/setup-miniconda#128]
Thanks for this nice project! I got stuck for a while because my run commands were not using a login bash shell. So the conda environment was not active. Would be helpful to warn about that and recommend something like the following in the yaml:

```
defaults:
  run:
    shell: bash -l {0}
```

**Comment by jaimergp** [comment]
This information is on the [README](https://github.com/conda-incubator/setup-miniconda#use-a-default-shell).

Do you mean a programmatic check in the action itself?

**Comment by goanpeca** [comment]
Hi @magland, thanks for the kind words :) 

@jaimergp indeed it is on the README, but that PR did not land on the [github action market place](https://github.com/marketplace/actions/setup-miniconda) 🙃

**Comment by magland** [comment]
Thanks for the quick reply. This is working perfectly for me now and it's a big help to my flow.

**Comment by goanpeca** [comment]
Awesome to hear that :)
