### ISSUE TITLE
BUG/QUESTION: Error: ESPIPE: invalid seek, read in Post cache conda step

### ISSUE THREAD

**Issue by fangchenli** [conda-incubator/setup-miniconda#131]
In the Post cache conda step, I got an error
```bash
Post job cleanup.
/bin/tar -cz -f /home/runner/work/_temp/e033d343-fc60-4104-9d25-04380c0faf29/cache.tgz -C /home/runner/conda_pkgs_dir .
Warning: read ECONNRESET
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: ESPIPE: invalid seek, read
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:167:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5) {
  errno: -29,
  code: 'ESPIPE',
  syscall: 'read'
}
```

Link to the [PR](https://github.com/pandas-dev/pandas/pull/38344).

I basically copied the example. Not if it's a bug or not.

**Comment by jaimergp** [comment]
It could be a temporary connection error (looking at that `ECONNRESET`). Is this happening consistently or sporadically?

**Comment by fangchenli** [comment]
> It could be a temporary connection error (looking at that `ECONNRESET`). Is this happening consistently or sporadically?

It happened only once. I'll reopen this if it keeps showing up.
