### ISSUE TITLE
valid mambaforge/miniforge parameters

### ISSUE THREAD

**Issue by jGaboardi** [conda-incubator/setup-miniconda#139]
**issue:**
I am trying out the new functionality with `mambaforge` from [Example 10](https://github.com/marketplace/actions/setup-miniconda#example-10-miniforge) and getting the following warning:

```
Warning: Unexpected input(s) 'miniforge-variant', 'miniforge-version', 'use-mamba', 
valid inputs are ['installer-url', 'miniconda-version', 'conda-version', 'conda-build-version', 
'environment-file', 'activate-environment', 'python-version', 'add-anaconda-token', 
'add-pip-as-python-dependency', 'allow-softlinks', 'auto-activate-base', 'auto-update-conda', 
'condarc-file', 'channel-alias', 'channel-priority', 'channels', 'show-channel-urls', 
'use-only-tar-bz2', 'remove-profiles', 'mamba-version', 'architecture']
```

The above warning](https://github.com/jGaboardi/tigernet/pull/57/checks?check_run_id=1635017442#step:4:1) seems to be due to the new parameters not being listed as valid inputs.

**associated files:**
* [workflow `.yml`](https://github.com/jGaboardi/tigernet/pull/57/files#diff-54c039feb42ef7c758e4cbc3aaa48971a1b41a1132399420b4c98d984ad62828)
* [actions run logs](https://github.com/jGaboardi/tigernet/actions/runs/456866329)

**Comment by bollwyvl** [comment]
Yeah, those features are unfortunately only available with
setup-miniconda@master. Release, and some new docs, forthcoming.

**Comment by jGaboardi** [comment]
> Yeah, those features are unfortunately only available with setup-miniconda@master. Release, and some new docs, forthcoming.

Ah, that makes sense. thanks for the quick reply!
