### ISSUE TITLE
Warning: Unexpected input(s) 'miniforge-variant', 'miniforge-version', 'use-mamba'

### ISSUE THREAD

**Issue by gboeing** [conda-incubator/setup-miniconda#142]
I'm following the readme's Mambaforge example, but I'm getting a warning and the action does not seem to successfully use mamba:
```
Warning: Unexpected input(s) 'miniforge-variant', 'miniforge-version', 'use-mamba', valid inputs are ['installer-url', 'miniconda-version', 'conda-version', 'conda-build-version', 'environment-file', 'activate-environment', 'python-version', 'add-anaconda-token', 'add-pip-as-python-dependency', 'allow-softlinks', 'auto-activate-base', 'auto-update-conda', 'condarc-file', 'channel-alias', 'channel-priority', 'channels', 'show-channel-urls', 'use-only-tar-bz2', 'remove-profiles', 'mamba-version', 'architecture']
```

I'm [using](https://github.com/gboeing/ppd599/actions/runs/500301464/workflow) `conda-incubator/setup-miniconda@v2`. You can see the log [here](https://pipelines.actions.githubusercontent.com/E23uL8Fd1SSX34ed3DYxnrzYZOU6caEJDpz54Z5yfg8rCGOKmp/_apis/pipelines/1/runs/19/signedlogcontent/3?urlExpires=2021-01-21T05%3A13%3A55.7556301Z&urlSigningMethod=HMACV1&urlSignature=CZc9za5goTOUrb3sEkZ6p7ej9O94SCYHe%2BTN8U065N8%3D).

**Comment by jaimergp** [comment]
Hi Geoff! I am afraid you are reading the latest README at `master`, where indeed you can find `use-mamba` but that's not released yet... Check the [README at the latest v2 tag to find the configuration values needed](https://github.com/conda-incubator/setup-miniconda/blob/v2.0.1/README.md#example-6-mamba) (i.e. `mamba-version: "*"`). Sorry for the confusion!

**Comment by gboeing** [comment]
Oh ok, thanks! I see how it's organized now. It may be useful to add a pointer on the master branch readme to where one can find documentation for the latest release. Thanks for all the great work on this action! SUPER useful.
