### ISSUE TITLE
Not setting miniforge-version silently uses bundled miniconda

### ISSUE THREAD

**Issue by xhochy** [conda-incubator/setup-miniconda#145]
If you only set `miniforge-variant` but not `miniforge-version`. The bundled `miniconda` is used with the current code on master.

**Comment by bollwyvl** [comment]
Brave developer! Thanks for reporting. I have also been using `master` in a few places, and hadn't encountered that yet. Will get on it.

**Comment by bollwyvl** [comment]
Was a pretty straightforward fix over on #146!
