### ISSUE TITLE
(Mamba/Mini)forge example not working?

### ISSUE THREAD

**Issue by janjagusch** [conda-incubator/setup-miniconda#149]
Hi, thanks for maintaining this action! 🚀 

I'm following [example 10 with Mambaforge](https://github.com/conda-incubator/setup-miniconda#example-10-miniforge). When running that example, I receive the following warning:

```sh
Warning: Unexpected input(s) 'miniforge-variant', 'miniforge-version', 'use-mamba', valid inputs are ['installer-url', 'miniconda-version', 'conda-version', 'conda-build-version', 'environment-file', 'activate-environment', 'python-version', 'add-anaconda-token', 'add-pip-as-python-dependency', 'allow-softlinks', 'auto-activate-base', 'auto-update-conda', 'condarc-file', 'channel-alias', 'channel-priority', 'channels', 'show-channel-urls', 'use-only-tar-bz2', 'remove-profiles', 'mamba-version', 'architecture']
```

Also, when I add an additional step

```yaml
- shell: bash -l {0}
   run: mamba install jupyterlab
```

I get the following error:

```sh
/home/runner/work/_temp/345635cc-bd38-43b6-a26a-1ca467ac05df.sh: line 1: mamba: command not found
```

**Comment by xhochy** [comment]
@janjagusch You need master for this, the features listed in the README are not yet released. As requested in https://github.com/conda-incubator/setup-miniconda/issues/106#issuecomment-780800170 I hope that @bollwyvl / @goanpeca might cut a smaller 2.1 release ;)

**Comment by janjagusch** [comment]
> #106 (comment)

Can confirm that by using `conda-incubator/setup-miniconda@e23d871804685e8c52189e5bd45e9145019f10af` the warning and the erorr disappear. Thanks @xhochy!

**Comment by goanpeca** [comment]
Will do on the weekend @xhochy  :)

**Comment by xhochy** [comment]
Thanks!
