### ISSUE TITLE
The action is deleting the .bashrc file

### ISSUE THREAD

**Issue by andfoy** [conda-incubator/setup-miniconda#151]
After taking a look at the logs when executing the action, it is possible to observe that the action deletes the .bashrc file from the home directory, which may cause unexpected behaviour when using other actions that may depend on variables defined there, an example of this, is the action-tmate, used to spawn a SSH session for remote debugging, which cannot be used alongside this action without doing some tweaks inside the tmux session. Here is the issue for reference: https://github.com/mxschmitt/action-tmate/issues/37

**Comment by andfoy** [comment]
This issue is also happening with MacOS machines.

**Comment by goanpeca** [comment]
You can set the `remove-profiles` option.

See: https://github.com/conda-incubator/setup-miniconda/blob/master/action.yml#L217

**Comment by GuillaumeQuenneville** [comment]
It might be more sensible to have it false as a default.

The intro docs for self-hosted runners https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners has the user setup the runner as their own user account. So running a github workflowwith this action wipes all the users rc files.

**Comment by goanpeca** [comment]
>It might be more sensible to have it false as a default.

Indeed but that will go for the 3.x version, since it was changing a default behavior.
