### ISSUE TITLE
Start a dev branch

### ISSUE THREAD

**Issue by bollwyvl** [conda-incubator/setup-miniconda#154]
To avoid long-standing and frequent complaints about Docs From The Future, I propose after we land #153 and do #106, we start a `develop` branch, and merge stuff to that.

**Comment by goanpeca** [comment]
Sounds good @bollwyvl 

Will do this!

**Comment by goanpeca** [comment]
Done!

**Comment by goanpeca** [comment]
Added a line on the CONTRIBUTING file to make PRs against `develop`. Need to double check as new PRs keep coming and update the target branch on existing PRs @bollwyvl

**Comment by bollwyvl** [comment]
Looks good. Will add _pr template_ to #159 so it's more front-and-center.

Can the existing dangling branches be deleted?

**Comment by goanpeca** [comment]
>Can the existing dangling branches be deleted?

Will do
