### ISSUE TITLE
[feat] Option to skip post conda-setup

### ISSUE THREAD

**Issue by yueyericardo** [conda-incubator/setup-miniconda#181]
Hi Developers,

Thanks for the great work!

Currently the post conda-setup step will `remove uncompressed packages to trim down cache folder` in `conda_pkgs_dir` folder , however I have a huge conda_pkgs_dir which needs 10 min to uncompress on a self-hosted server.

Is that possible to have an option to skip the post step? I'm currently renaming the `conda_pkgs_dir` folder to a different dirname to avoid the post step to be ran, but it's ugly.

Thanks!
Richard

**Comment by goanpeca** [comment]
Hi @yueyericardo, thanks for the suggestion.

It does make sense :)

**Comment by goanpeca** [comment]
Implemented on #234
