### ISSUE TITLE
Cannot reproduce locally with act

### ISSUE THREAD

**Issue by lmmx** [conda-incubator/setup-miniconda#182]
Edit: please ignore, asked in error (problem was not due to setup from this package).

**Comment by lmmx** [comment]
@spenczar I made notes at https://github.com/lmmx/devnotes/wiki/Running-GitHub-CI-locally-with-nektos-act-(Docker)-in-LXC and the repo in question was [range-streams](https://github.com/lmmx/range-streams/blob/master/.github/workflows/master.yml). See also [this script under `tools/` in the top-level of the repo](https://github.com/lmmx/range-streams/blob/master/tools/github/install_miniconda.sh)

I think I didn't initially appreciate the fact that despite the name setup-miniconda does not put miniconda on your system (or runner), it just sort of 'recognises' the one already set up, so to this end I just prepared by installing miniconda if there was no `INSTALL_MINICONDA` flag set, which I called the "gate".

- The GitHub runner's environment variables (for my chosen image, Ubuntu 20.04) are given [here](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md)
- I call act as `sudo act --env CONDA=$CONDA --env INSTALL_MINICONDA=$CONDA` which provides the environment variable `$INSTALL_MINICONDA` thus "gating" that part of the workflow, you get the idea.

As I recall, the presence of that env variable starts the installer, and the value of the env var tells it where to put it.

This way you can avoid slowing down your CI by it installing conda when it doesn't need it (it comes in the image). Hope that helps, let me know if anything is unclear in that doc

**Comment by scherroman** [comment]
Thanks @lmmx, for me using `miniconda-version: 'latest'` actually fixed my issue when running locally with act, causing it to download miniconda when it wasn't found. Really had to hunt down this info, kept running into the cryptic error `Error: No installed conda 'base' enviroment found at`.

Also relevant to issue #203
