### ISSUE TITLE
anaconda command not found

### ISSUE THREAD

**Issue by romainsacchi** [conda-incubator/setup-miniconda#183]
Probably a very stupid mistake on my end, but I keep having the following issue, when trying to upload a package after `conda build`:

`Total time: 0:05:10.6
CPU usage: sys=0:00:00.8, user=0:00:07.7
Maximum memory usage observed: 108.0M
Total disk usage observed (not including envs): 213.0K
/home/runner/work/_temp/b0e748d6-e2f7-4807-b9c5-75b8aa6bcd5f.sh: line 19: anaconda: command not found
Error: Process completed with exit code 127.`

And here is my script:
'''
conda:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,cmutel,konstantinstadler,haasad,pascallesage,romainsacchi
          allow-softlinks: true
          channel-priority: strict
          auto-update-conda: true
          conda-build-version: 3.21.4
          activate-environment: test

      - name: Conda info
        shell: bash -l {0}
        run: conda info

      - name: Publish distribution 📦 to Anaconda if Push
        shell: bash -l {0}

        run: |
         
          PKG_NAME=premise
          mkdir ~/conda-bld
          conda config --set anaconda_upload no

          conda build "conda/"

          anaconda -t ${{ secrets.ANACONDA_CLOUD }} upload -u ${{ secrets.CONDA_USERNAME }} /usr/share/miniconda/conda-bld/noarch/$PKG_NAME-$VERSION-py_0.tar.bz2 --force
'''

Everything runs fine until the last line (`anaconda upload`), which is not recognized.

Any hint would help a lot.
Thanks.

**Comment by jaimergp** [comment]
Can you list your environment? `anaconda-client` is not part of the default `base` environment and would need to be installed explicitly.

**Comment by romainsacchi** [comment]
Ahah, that was it. Adding `conda install anaconda-client` solved it. Thanks!
