### ISSUE TITLE
Allow quiet installation

### ISSUE THREAD

**Issue by berquist** [conda-incubator/setup-miniconda#184]
The output from `conda install` contains progress bars which make the workflow output very noisy. It would be nice if `quiet` was added as an action option, which could then be passed as `conda install --quiet`.

**Comment by jaimergp** [comment]
I think you can pass custom `.condarc` files, which would allow you to specify this behaviour!

https://github.com/conda-incubator/setup-miniconda#example-3-other-options

**Comment by berquist** [comment]
I thought so too, but according to https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html you can only quiet `conda-build` via config, not `conda`. (This is a `conda` bug, in my opinion, but I can't quickly find an issue in their repo.)

**Comment by jaimergp** [comment]
Oh, you are right. This is for [`conda-build`](https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#limit-build-output-verbosity-conda-build-3-0-quiet). That's... surprising. I couldn't find a relevant issue in their tracker either, I'll create one.

@conda-incubator/setup-miniconda, what do you think about adding a `conda-cli-flags` and `conda-subcommand-cli-flags` keys to add arbitrary flags to the subprocesses?

```
conda _____ install ______ a-package
#       ^ cli-flags    ^subcommand-cli-flags
```

**Comment by jaimergp** [comment]
Ah wait, there is one apparently. Check the raw configuration here, you can use `quiet`?

https://docs.conda.io/projects/conda/en/latest/configuration.html

**Comment by goanpeca** [comment]
Thanks for the feedback @berquist !

@jaimergp should we close this or do you think we should add a new feature?

Thanks!

**Comment by jaimergp** [comment]
I think we can close this. @berquist feel free to re-open it if needed!
