### ISSUE TITLE
develop and master branches have diverged

### ISSUE THREAD

**Issue by ktbarrett** [conda-incubator/setup-miniconda#202]
Looks like some PRs came in on the develop branch and others on the master branch. I recommend the two be merged and a single development branch be select and the other locked.

**Comment by goanpeca** [comment]
@ktbarrett you are right, need to do that clean up. Thanks for the heads up!

**Comment by goanpeca** [comment]
develop is now in sync with master. 

Develop should carry all the new PRs moving forwawd.

And now moving to use main also, and deprecate master.

Cheers!
