### ISSUE TITLE
Recently the schema become invalid for Linux machines

### ISSUE THREAD

**Issue by Borda** [conda-incubator/setup-miniconda#214]
Hello,
 first, thank you for your great action, and second not sure if it is really an issue on your side
We have been successfully using the COnda environment to our GH action CI for Linux-based machines which require to set `shell: bash -l {0}` to be properly running Conda environment...
At the same time, we are testing all GH action schemas if they are valid with `check-jsonschema` and it suddenly starts to fail...

This is the command for validation we are using
```bash
check-jsonschema .github/workflows/*.yml --schemafile "https://json.schemastore.org/github-workflow"
```
Thank you for any advice or suggestion :rabbit:

**Comment by bollwyvl** [comment]
While widely-used, the schema in schemastore aren't usually official... and I don't know of an official one from github. What errors are you actually seeing? What workflow are you actually validating? A link would be sufficient... or a redacted version as a gist that still exhibits the condition.

**Comment by bollwyvl** [comment]
Perhaps this change will fix your issue (once deployed): https://github.com/SchemaStore/schemastore/pull/2070

**Comment by Borda** [comment]
Well, I was getting the same error regathers if the `shell: bash -l {0}` was used in each run or as default...
The error was following:
```
Schema validation errors were encountered.
  .github/workflows/ci_test-conda.yml::$.defaults.run.shell: 'bash -l {0}' is not valid under any of the given schemas
```
but tank you for clarification and I will which my investigation elsewhere :]
