### ISSUE TITLE
Update of workflow schema breaks using login shell in defaults

### ISSUE THREAD

**Issue by Nieju** [conda-incubator/setup-miniconda#216]
All tutorials here are using
```
    defaults:
      run:
        shell: bash -l {0}
```

This breaks since there was an update to the schema
<img width="874" alt="image" src="https://user-images.githubusercontent.com/77630834/152770322-03df2286-c907-41ab-b599-fa254038eb77.png">

What's an alternative, now?

Schema: https://json.schemastore.org/github-workflow.json

**Comment by goanpeca** [comment]
Hi @Nieju that is unfortunate, thanks for reporting. Will open an issue on the Github help.

**Comment by goanpeca** [comment]
@Nieju I no longer see this issue, let me know if this is not the case.

Thanks!
