### ISSUE TITLE
Bash error on fail not included in README

### ISSUE THREAD

**Issue by henryiii** [conda-incubator/setup-miniconda#227]
The default shells on GitHub Actions set `-e` for you, so that something like this:

```
some_broken_command
rm _cache
```

Will fail. However, the replacement shell recommended in the README will not do this, and will pass because the final command passes. For better user experience and matching the default behavior, `-e` should be added to the shell recommendation shown. This caused an issue https://github.com/scikit-build/scikit-build/issues/698 at least.

I think it should be something like:

```yaml
shell: bash -el {0}
```

I'm not sure about the other common additions (`-euxo pipefail`), but I know that GitHub Actions does include `-e` by default. It was considered a bug that Azure Pipelines does not set `-e` by default, and was fixed when GitHub Actions was released.

**Comment by goanpeca** [comment]
Hi @henryiii, doing some "spring cleaning" and triage, indeed seems like something we should we doing. Will update README

**Comment by goanpeca** [comment]
@conda-incubator/setup-miniconda just to double check, do you all agree with updating the instructions on the README and examples to include  `-el` ?

**Comment by jaimergp** [comment]
Definitely!

**Comment by goanpeca** [comment]
Fixed!
