### ISSUE TITLE
Switching `master` to `main`

### ISSUE THREAD

**Issue by jakirkham** [conda-incubator/setup-miniconda#231]
Would be good to switch `master` to `main` on this repo.

As some users pin to `@master` in workflows, it probably can't be removed, but it would be good to include a deprecation notice with `@master` (maybe just a message that gets reverted in `main`).

**Comment by goanpeca** [comment]
Thanks for the suggestion @jakirkham !

**Comment by goanpeca** [comment]
Fied already!

**Comment by jakirkham** [comment]
Thanks Gonzalo! 🙏
