### ISSUE TITLE
setting python-version to 3.10 uses 3.1 instead

### ISSUE THREAD

**Issue by jacksund** [conda-incubator/setup-miniconda#232]
I'm trying to move my CI over to this github action, but it looks like there's a bug with python 3.10. My CI will fail because this action incorrectly installs python 3.1 instead of 3.10.

This was an error in a recent conda version that's since been fixed, but using `auto-update-conda: true` doesn't resolve this issue. Maybe this action starts-up with an older version which causes the bug...? In my current CI (without using this action), I need to make sure I run `conda update -n base -c defaults conda` ([link](https://github.com/jacksund/simmate/blob/c9d9aa15c6ec0132a61943967fe038af2a02e588/.github/workflows/lint-and-test.yml#L32)) before installing.

Here are some links to my repo and workflow files that might be useful in troubleshooting:
- [workflow file](https://github.com/jacksund/simmate/blob/5d1435e32dab527943450bbc9ca2aa8baf38774e/.github/workflows/lint-and-test.yml#L31)
- [example error for workflow](https://github.com/jacksund/simmate/runs/6540442493?check_suite_focus=true#step:4:4)
- [PR attempting to implement this action](https://github.com/jacksund/simmate/pull/167)

Would anyone be able to help with this? Thanks in advance for any help😄

**Comment by traversaro** [comment]
I think you need to write `"3.10"`, not `3.10` but I did not check.

**Comment by mattwthompson** [comment]
Yes, please use `"3.10"` because of how the workflow file parsed (i.e. the same issue [here](https://github.com/actions/setup-python/issues/160)).

**Comment by jacksund** [comment]
that worked. Thanks for the quick and easy fix!
