### ISSUE TITLE
Fatal error - cygheap base mismatch detected (Git)

### ISSUE THREAD

**Issue by H0R5E** [conda-incubator/setup-miniconda#239]
Hi, I am getting sporadic failures running conda with the setup-miniconda action on Windows runners. The installation step goes OK, but when I call `conda info`, to verify the installation, Actions wigs out with the following message:

```
0 [main] dirname (4404) C:\Miniconda\envs\_snld3d\Library\usr\bin\dirname.exe: *** fatal error - cygheap base mismatch detected - 0x18034B408/0x180349408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
Error: Process completed with exit code 127
```

The failed job is [here](https://github.com/H0R5E/SNL-Delft3D-CEC-Verify/runs/6779322690?check_suite_focus=true#step:5:14) and the associated workflow is [here](https://github.com/H0R5E/SNL-Delft3D-CEC-Verify/actions/runs/2456298596/workflow). The problem is not unique to this workflow.

Many thanks,

Mat

**Comment by goanpeca** [comment]
Hi @H0R5E, thanks for the report.

We will take a look at it, but being sporadic, makes it hard to debug :-\

**Comment by H0R5E** [comment]
@goanpeca, thanks for getting back to me. I've done a little more investigation and it seems to be specific to the environment I am trying to recreate. I have created a dedicated test repo [here](https://github.com/H0R5E/setup-miniconda-test) and the failure seems to be generated by something in the [`enviroment.yaml`](https://github.com/H0R5E/setup-miniconda-test/blob/main/environment.yaml) file.

Do you have any clue which package might be triggering this? If not I will forensically remove things until it works, I guess. :open_mouth:

**Comment by H0R5E** [comment]
OK, it actually didn't take me too long to find. It's Git. Specifically,

```
git                       2.35.3               h57928b3_0    conda-forge
```

Do you think this is an upstream issue?

**Comment by H0R5E** [comment]
Closing, as the problem [seems to have resolved itself](https://github.com/H0R5E/setup-miniconda-test/actions/runs/3043374940/jobs/4902568235).
