### ISSUE TITLE
create base environment without python?

### ISSUE THREAD

**Issue by AndrewAnnex** [conda-incubator/setup-miniconda#241]
I want to be able to set up conda environments without python for a project but the action appears to insert a python version regardless of the absence of `python-version` or python in a yaml file. I suppose I could just allow the creation of a simple base environment, then make the other environment, but that would be a bit wasteful of worker time

**Comment by mattwthompson** [comment]
Could you elaborate a bit on the use case?

AFAIR Miniconda ships with Python included, so I'm not sure what this would look like.

**Comment by AndrewAnnex** [comment]
I have a project that utilizes a complicated toolkit called isis https://github.com/USGS-Astrogeology/ISIS3 that is mainly c++ and interacts badly with any user specified or overridden python version when using conda (see the yaml used in my github ci workflow https://github.com/AndrewAnnex/asap_stereo/blob/b6b6adc04dacefeafbc1f65227154bf4e806d105/isis.yml) 

one can also make empty conda environments by not specifying an environment e.g. `conda create -n emptyenv`, so in principal it could be useful to allow this behavior with this action

**Comment by goanpeca** [comment]
@AndrewAnnex thanks for the report. If you use the environment.yaml option to list the dependencies, and no python is listed in there, is it still installing python? Wanted to double check

**Comment by AndrewAnnex** [comment]
@goanpeca it looks like I may have been wrong. I removed the strict solve option and I am now able to solve the conda environment, which was the motivation for not including python in the first place, but also the project I site above does depend on python anyways (I had forgotten) so I'll close this issue for now.
