### ISSUE TITLE
conda-auto-update default arg conflict with description

### ISSUE THREAD

**Issue by thisiswhereitype** [conda-incubator/setup-miniconda#243]
[Relevant docs](https://github.com/conda-incubator/setup-miniconda/blob/e81abac10ce2c37423b54eae5af93aa3b4d3475c/action.yml#L148)

On the line above it argument is said to be true by default but below it is indicated to be false.

Opened issue as not clear what was the intention by author

**Comment by goanpeca** [comment]
Hi @thisiswhereitype thanks!

Indeed we need to correct that!

**Comment by goanpeca** [comment]
Fixed by https://github.com/conda-incubator/setup-miniconda/commit/8de554edbf0b50af8180722bf8799966ada8923f
