### ISSUE TITLE
Node.js 12 deprecation warning

### ISSUE THREAD

**Issue by asmaloney** [conda-incubator/setup-miniconda#248]
I'm getting the following warning:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: conda-incubator/setup-miniconda

Not sure how these actions work. ~~Does updating **@types/node** in `package.json` solve it?~~

**Edit:** I see `using: "node12"` in action.yml - that's (at minimum) what needs to change.

(Or is this project dead?)

**Comment by goanpeca** [comment]
Hi @asmaloney will update the action and make a new release!

Thanks for the heads up

>(Or is this project dead?)

It is not :) !

**Comment by asmaloney** [comment]
> It is not :) !

Great news! 🎆 

Thank you so much for this.

**Comment by jakirkham** [comment]
What does it entail to update? Changing this line? Or are there other things needed?

https://github.com/conda-incubator/setup-miniconda/blob/e81abac10ce2c37423b54eae5af93aa3b4d3475c/package.json#L44

**Comment by alessiostalla** [comment]
> What does it entail to update? Changing this line? Or are there other things needed?
> 
> https://github.com/conda-incubator/setup-miniconda/blob/e81abac10ce2c37423b54eae5af93aa3b4d3475c/package.json#L44

That line only affects type-checking TS code that refers to Node APIs. The line to change is
https://github.com/conda-incubator/setup-miniconda/blob/e81abac10ce2c37423b54eae5af93aa3b4d3475c/action.yml#L6

**Comment by jakirkham** [comment]
Maybe someone here can review PR ( https://github.com/conda-incubator/setup-miniconda/pull/252 )?
