### ISSUE TITLE
Error: channels.slice.reverse is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by gauteh** [conda-incubator/setup-miniconda#255]
I started getting this error today for configs that used to work. Tried older miniforge versions (4) and older setup-miniconda versions (2.0.0) but doesn't make a difference. Is there something else that can be changed?

https://github.com/OpenDrift/trajan/actions/runs/3435085578/jobs/5727041966

**Comment by goanpeca** [comment]
Hi @gauteh sorry for the issues. Could you link to the workflow file so we can try to replicate?

Thanks!

**Comment by gauteh** [comment]
https://github.com/OpenDrift/trajan/blob/main/.github/workflows/tests.yml thanks for taking a look!

**Comment by gauteh** [comment]
Turns out this was caused by a typo in the environment file.

**Comment by goanpeca** [comment]
Hi @gauteh, awesome :). glad you found the issue!
