### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jakirkham** [conda-incubator/setup-miniconda#260]
There are a number of fixes that have gone in. Also looks like it has been quite a while since the last release. Would it be possible to make a new release?

**Comment by goanpeca** [comment]
Hi @jakirkham, version 2.2.0 has been released

https://github.com/conda-incubator/setup-miniconda/releases/tag/v2.2.0

Closing :)

**Comment by jakirkham** [comment]
Awesome thanks Gonzalo! 🙏
