### ISSUE TITLE
nothing provides requested pandas 1.5.2

### ISSUE THREAD

**Issue by YarShev** [conda-incubator/setup-miniconda#264]
Hi guys,

We (Modin) use `conda-incubator/setup-miniconda@v2` to install packages for the development environment in our GH Actions workflows for testing ([e.g., here](https://github.com/modin-project/modin/blob/317bd75d0677c0ae1a400f7313953ee6638185ac/.github/workflows/ci.yml#L186)). Pandas recently released 1.5.2 version and it is already available in conda-forge ([link](https://anaconda.org/conda-forge/pandas)). However, using our [environment-dev.yml](https://github.com/modin-project/modin/blob/master/environment-dev.yml) to install dependencies in GH Actions workflows we see the error.

```
Encountered problems while solving:
    - nothing provides requested pandas 1.5.2
 ```

See the related issue in our repo - https://github.com/modin-project/modin/issues/5256.

We would be really appreciate if you could tell us what is going on wrong. It really stops us to make a release and probably others who is experiencing the issue.

Thanks in advance.

**Comment by goanpeca** [comment]
Hi @YarShev, even when packages show up on forge https://anaconda.org/conda-forge/pandas, it might take a while for the metadata that conda forge relies on to get updated. This should be a matter of hours hopefully and it is not related with setup-miniconda.

I just tried locally installing pandas and I get the same error.

<img width="639" alt="Screen Shot 2022-11-24 at 11 42 00 AM" src="https://user-images.githubusercontent.com/3627835/203833458-1cf7b334-abda-466b-a783-e1f64a3778bc.png">

**Comment by YarShev** [comment]
Hi @goanpeca, it is very strange. I was able to install pandas 1.5.2 locally even yesterday.

**Comment by bollwyvl** [comment]
unless specifically overridden per-feedstock, `conda-forge` now [only generates `.conda` files](https://github.com/conda-forge/conda-forge.github.io/issues/1586). if you've configured `use-only-tar-bz2: true` for caching in the workflow, it's not going to find any new packages.

**Comment by YarShev** [comment]
@bollwyvl, `use-only-tar-bz2: false` seems to be working. Thanks.

What do you mean by "overridden per-feedstock"?

**Comment by goanpeca** [comment]
>What do you mean by "overridden per-feedstock"?

It means that unless othwerwise specified on each conda forge recipe feedstock, only .conda artifacts will be generated.

**Comment by goanpeca** [comment]
Last time I checked conda was always redownloading everything if .conda files were used, maybe it has been fixed in recent versions, otherwise caching will no longer work with this action (until that is fixed... )

**Comment by YarShev** [comment]
@goanpeca, got it, thanks you a lot. Closing the issue.

**Comment by michaelosthege** [comment]
This section in the docs specifies how to configure a feedstock to output `.tar.bz2` artifacts: https://conda-forge.org/docs/maintainer/conda_forge_yml.html#conda-build
