### ISSUE TITLE
Installing multiple python envs in the same CI

### ISSUE THREAD

**Issue by calvinp0** [conda-incubator/setup-miniconda#283]
Hi,

For our code, we use two different environments during the test. What I mean is, we have a main environment, `t3_env` and then when we are testing it, the code will create a bash file that has the contents

```bash
conda activate rmg_env

python ~\Code\RMG-Py\RMG.py input.yml
```

This script will run another code of ours that we have git cloned during the CI and it will then output a file called species.txt, which then our original code will read it back in and continue on completing the tests.

I am having difficult with being able to active the second environment in the bash script, because even though I do something like this:

```actions
    - name: Install RMG
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: RMG-Py/environment.yml
        miniforge-variant: Mambaforge
        miniforge-version: latest
        activate-environment: rmg_env
        python-version: 3.7
        use-mamba: true
    - name: Install T3 
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file:  environment.yml
        miniforge-variant: Mambaforge
        miniforge-version: latest
        activate-environment: |
          t3_env
          rmg_env
        python-version: 3.7
        use-mamba: true
```

It will have trouble activating the rmg_env during the testing phase.

Is there something else I am meant to do to make this work? Is it possible?

**Comment by goanpeca** [comment]
@calvinp0 thanks for posting the question. I do not think we have ever used this action like this (with 2 separate steps running the same action, not sure it will even work correctly)

I would just use it to create one environment and then run the creation of the other environment as a series of steps that do

`conda create -n the-other-env etc...`

**Comment by calvinp0** [comment]
Thanks @goanpeca, that's what I ended up doinng in the end. I did attempt to do 2 separate steps but it didn't work correctly. The second step superceded the first step so then our CI couldn't see the environment installed in the first step.

Thanks again!
