### ISSUE TITLE
miniforge-version support for ARM64

### ISSUE THREAD

**Issue by a-cesari** [conda-incubator/setup-miniconda#312]
Dear all,
I'm trying to setup miniforge and to use mamba on a arm64 runner on Github Workflow.
Here my setup:

![image](https://github.com/conda-incubator/setup-miniconda/assets/6312038/944b5ecf-6b7d-4275-bbe4-e97b4c9502ae)

However the ARM64 arch is not supperted when used with the miniforge-version keyword (while with miniconda it's possible).

By the way I'm asking this because my miniconda setup suddenly stopped to work giving me this error:

![image](https://github.com/conda-incubator/setup-miniconda/assets/6312038/79c67f16-26a3-4d27-9985-0743ed19a5ff)

Thanks for your help!

**Comment by jaimergp** [comment]
Hi, thanks for the report! In the meantime, you can probably get by with using the direct url for latest, via `installer-url`, I think?

```
https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-aarch64.sh
```

**Comment by a-cesari** [comment]
Thanks @jaimergp ,

the installation it's now working. However I get an error when calling mamba activate myenv saying that I should run mamba init (even if I'm using bash -el {0} which was working for conda activate command).
Conda activate works well.

**Comment by traversaro** [comment]
> As of today, github has made M1 ARM64 available : https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/ . It would be great if setup-miniconda would support "architecture: arm64" for it

If anyone is interested in a quick workaround until it is properly supported, as suggested earlier by @jaimergp it is possible to use installer-url, something like the following seems to be working fine:
~~~
    - uses: conda-incubator/setup-miniconda@v3
      if: matrix.os != 'macos-14'
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest

    - uses: conda-incubator/setup-miniconda@v3
      if: matrix.os == 'macos-14'
      with:
        installer-url: https://github.com/conda-forge/miniforge/releases/download/23.11.0-0/Mambaforge-23.11.0-0-MacOSX-arm64.sh
~~~

**Comment by jezdez** [comment]
I've opened https://github.com/conda-incubator/setup-miniconda/pull/331 to fix it. Feel free to trial with:

```
- uses: jezdez/setup-miniconda@arm64
```
