### ISSUE TITLE
Windows runs with custom installer throw "cygpath is not available" warning

### ISSUE THREAD

**Issue by dokempf** [conda-incubator/setup-miniconda#354]
I do use the action with a custom installer URL. In the "Initializing conda shell integration" step, I get multiple warnings like this:

```
WARNING conda.activate:native_path_to_unix(1018): cygpath is not available, fallback to manual path conversion
  Warning: WARNING conda.activate:native_path_to_unix(1018): cygpath is not available, fallback to manual path conversion
```

This is a bit annoying, because these warnings are also shown as annotations in the workflow run summary.

It sounds a bit like the action should ensure that `cygpath` is available?

**Comment by moorepants** [comment]
I see this here also: https://github.com/moorepants/anaconda-dee-config/actions/runs/9467706430

**Comment by torokati44** [comment]
Same here: https://github.com/ruffle-rs/ruffle/actions/runs/9801165444

**Comment by torokati44** [comment]
Oh, and this only takes 2-3 seconds:
https://github.com/ruffle-rs/ruffle/actions/runs/9849341093/job/27192865258

As opposed to 1-2 minutes before on Windows:
https://github.com/ruffle-rs/ruffle/actions/runs/9848198629/job/27189693193
https://github.com/ruffle-rs/ruffle/actions/runs/9848099881/job/27189421366

**Comment by oleksandr-pavlyk** [comment]
IntelPython/dpctl projects is affected too: https://github.com/IntelPython/dpctl/actions/runs/9946592345

**Comment by oleksandr-pavlyk** [comment]
Could this be related to https://stackoverflow.com/questions/12620306/cygpath-not-able-to-convert-windows-path-to-linux-path ?

**Comment by marcoesters** [comment]
I think it is this warning: https://github.com/kenodegard/conda/blob/cefc611cfa4208d8a898a74e57ffb0166c78ce2f/conda/activate.py#L1034

I think this warning can be ignored - Windows installers rarely use cygpath during the installation. I created a PR: #362
