### ISSUE TITLE
GH Actions with this action runs on http error 429 since yesterday

### ISSUE THREAD

**Issue by Rubber1Duck** [conda-incubator/setup-miniconda#357]
I have son GH actions runnig over a year , with no problems , but since yesterday all these action runs on an error.
see log

Run conda-incubator/setup-miniconda@v2
  with:
    auto-activate-base: false
    activate-environment: covid
    python-version: 3.11
    miniconda-version: latest
    channels: conda-forge,defaults
    auto-update-conda: false
    remove-profiles: true
    architecture: x64
    clean-patched-environment-file: true
    run-post: true
Gathering Inputs...
Creating bootstrap condarc file in /home/runner/.condarc...
Ensuring installer...
  Can we use bundled Miniconda?
  Can we download a custom installer by URL?
  Can we download Miniconda?
  ... will download Miniconda.
  Miniconda3-latest-Linux-x86_64.sh
  Ensuring Installer...
  Checking for cached Miniconda3@latest...
  Did not find Miniconda3-latest-Linux-x86_64.sh latest in cache
  Unexpected HTTP response: 429
  Waiting 18 seconds before trying again
  Unexpected HTTP response: 429
  Waiting 14 seconds before trying again
Error: Unexpected HTTP response: 429

**Comment by mmcky** [comment]
+1 -- it looks like the anaconda server is giving me the same response. 

https://repo.anaconda.com/miniconda/

```
{
"reason":"terms of service rate limit exceeded",
"message":"It has been determined that you are in violation of the Anaconda terms of service, and may not be licensed for usage."
}
```

**Comment by egillax** [comment]
It seems this is an issue at anaconda's end and they are looking into it:

>Just wanted to confirm that we’re looking into this issue - we’ll get back to you ASAP.

From [here](https://community.anaconda.cloud/t/cant-download-anaconda-say-violating-terms-of-service/76074/14)

**Comment by wpreimes** [comment]
Seems to work again

**Comment by Rubber1Duck** [comment]
> It seems this is an issue at anaconda's end and they are looking into it:
> 
> > Just wanted to confirm that we’re looking into this issue - we’ll get back to you ASAP.
> 
> From [here](https://community.anaconda.cloud/t/cant-download-anaconda-say-violating-terms-of-service/76074/14)

Yes it seems so, and it seems to work again, now.
close this issue now
