### ISSUE TITLE
Setup failure when ensuring installer

### ISSUE THREAD

**Issue by jeremyfowers** [conda-incubator/setup-miniconda#358]
I see the following problem with both the v2 and v3 action:

```
Ensuring installer...
  Can we use bundled Miniconda?
  Can we download a custom installer by URL?
  Can we download Miniforge?
  Can we download Miniconda?
  ... will download Miniconda.
  Miniconda3-latest-Windows-x86_64.exe
  Ensuring Installer...
  Checking for cached Miniconda3@latest...
  Did not find Miniconda3-latest-Windows-x86_64.exe latest in cache
  Unexpected HTTP response: 429
  Waiting 17 seconds before trying again
  Unexpected HTTP response: 429
  Waiting 14 seconds before trying again

Error: Unexpected HTTP response: 429
Error: The operation was canceled.

```

Here is an example execution: https://github.com/onnx/turnkeyml/actions/runs/9705288699/job/26787090463?pr=174

This happens no matter how many times I retry. The problem started yesterday and it persists today. What do I do? This is blocking development of my project.

**Comment by robinjhuang** [comment]
@jeremyfowers Why did you close this? Also got the same error...

**Comment by jeremyfowers** [comment]
@robinjhuang I closed the issue because it started working for me again. I have no clue why, as I didn't make any changes.
