### ISSUE TITLE
`pre_install.sh` fails with code 1 at setup-miniconda@v3/installer step

### ISSUE THREAD

**Issue by valeriupredoi** [conda-incubator/setup-miniconda#372]
Hi folks, I am 100% sure this not you, but core conda, have a look at our [failed GA](https://github.com/ESMValGroup/ESMValTool/actions/runs/11337121154/job/31528222510) - this is happening across the board for us, and it's been happening since last night, also, we've seen this about two weeks ago, and within 24h it resolved itself. Just a heads up in case others start reporting this, and also, any clue what's the matter? Many thanks for your great Actions 🍻

**Comment by jaimergp** [comment]
I think you are referring to the Mambaforge brownouts. Please read the announcement in the warning text.

More details at https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/, but TLDR: Use miniforge instead of mambaforge.

**Comment by valeriupredoi** [comment]
> I think you are referring to the Mambaforge brownouts. Please read the announcement in the warning text.
> 
> More details at https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/, but TLDR: Use miniforge instead of mambaforge.


@jaimergp whoa this is most useful, mate, cheers! I was brushing all this under a conda failure carpet, but in this case, we have to take action! I'll be onto this, many thanks for the pointer 🍺
