### ISSUE TITLE
Expose configuration options as inputs

### ISSUE THREAD

**Issue by goanpeca** [conda-incubator/setup-miniconda#4]
Some of these options could e exposed directly as inputs to make life easy on subsequent commands

https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#general-configuration

Like: 
- `channels`
- `default_channels`

...

**Comment by sodre** [comment]
@goanpeca, 
Thanks for working on this. It might be useful to also expose the ability to load a .github/.condarc file if it exists. Then the order can be left up to you, either the file loads first and the options in the action yaml override those, or the other way around.

**Comment by goanpeca** [comment]
There is an option to load a file aleeady. See the Readme

**Comment by sodre** [comment]
I missed it the first time I saw it! Thank you so much!

**Comment by dcdenu4** [comment]
It would be great to directly specify the `channels` and other inputs as to avoid carrying around a condarc file in the repo.

**Comment by goanpeca** [comment]
Indeed! I added the config file since that was the broader solution and then Incould start adding more options :-).

In a work or so I will make a new release

**Comment by goanpeca** [comment]
@dcdenu4 I do have some questions here. Channels has the option of appending and prepending, so should both options be exposed or using channels should prepend (give higher priority always above defaults)

This is what I feel would work best, but wanted to hear some comments.

**Comment by dcdenu4** [comment]
@goanpeca I like the prepend approach of giving what's listed priority, in the order it's listed. That is what would be desirable for our use case. The reason we are specifying our own channels is because we want those used over the defaults first.

**Comment by goanpeca** [comment]
Hi @dcdenu4. Just made the release. Let me know how it goes.
