### ISSUE TITLE
too long setup phase & caching

### ISSUE THREAD

**Issue by Borda** [conda-incubator/setup-miniconda#54]
Quite frequently we have failing test just after init of Conda environment. From the log, it seems to be cancelled but there is no obvious reason why it happened and I do not think that anyone did it manually...
This is a link to one of this pseudo cancelled jobs
https://github.com/PyTorchLightning/pytorch-lightning/pull/2486/checks?check_run_id=847392959
and this is the cut log
```
2020-07-07T21:19:14.8870348Z ##[group]Run goanpeca/setup-miniconda@v1.6.0
2020-07-07T21:19:14.8870519Z with:
2020-07-07T21:19:14.8870641Z   auto-activate-base: false
2020-07-07T21:19:14.8870762Z   miniconda-version: 4.7.12
2020-07-07T21:19:14.8870877Z   python-version: 3.7
2020-07-07T21:19:14.8870975Z   environment-file: environment.yml
2020-07-07T21:19:14.8871096Z   activate-environment: pl-env
2020-07-07T21:19:14.8871213Z   use-only-tar-bz2: true
2020-07-07T21:19:14.8871332Z   auto-update-conda: false
2020-07-07T21:19:14.8871449Z   remove-profiles: true
2020-07-07T21:19:14.8871561Z ##[endgroup]
2020-07-07T21:19:14.9800149Z 
2020-07-07T21:19:14.9800380Z # 
2020-07-07T21:19:14.9800612Z # Downloading Miniconda...
2020-07-07T21:19:14.9800680Z 
2020-07-07T21:19:14.9805777Z ##############################
2020-07-07T21:19:14.9805898Z 
2020-07-07T21:19:14.9809615Z Miniconda3-4.7.12-Linux-x86_64.sh
2020-07-07T21:19:15.9515494Z Saving cache...
2020-07-07T21:19:16.6935049Z 
2020-07-07T21:19:16.6935850Z # Installing Miniconda...
2020-07-07T21:19:16.6936568Z #########################
2020-07-07T21:19:16.6937014Z 
2020-07-07T21:19:16.6999519Z [command]/usr/bin/bash /home/runner/work/_temp/64e1902d-ffc0-4207-b662-496b67f44c2e.sh -b -p /usr/share/miniconda3
2020-07-07T21:19:17.3422900Z PREFIX=/usr/share/miniconda3
2020-07-07T21:19:18.1341837Z Unpacking payload ...
2020-07-07T21:19:19.3115710Z 
2020-07-07T21:38:25.4494202Z   0%|          | 0/35 [00:00<?, ?it/s]
2020-07-07T21:38:25.4781118Z ##[error]The operation was canceled.
```
Any idea what could be happening there?

**Comment by goanpeca** [comment]
>Any idea what could be happening there?

Not really, this is the first time I see this.

**Comment by Borda** [comment]
ok, found the source, my bad... I have set a timeout for 20 min...
on the other hand is there a reason why it sometimes takes much longer than usual to setup the env... for the most tests, it takes 10min but these are twice as long...

**Comment by goanpeca** [comment]
@Borda any reason to test things with a new downloaded miniconda? If you do not provide that key in the action, it will used the bundled miniconda that comes with the runner.

**Comment by Borda** [comment]
I wanted to use some version lower than 4.8 as these latest versions do not forward exit status...
I have added also some caching from your readme which seems not to work... (maybe I made a mistake somewhere)
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/workflows/pt-conda.yml#L40-L46
I assume that propper caching may solve our issue too, right?

**Comment by goanpeca** [comment]
>I wanted to use some version lower than 4.8

Well why not trying to downgrade miniconda ? use the bundled one, but downgrade.

>I assume that propper caching may solve our issue too, right?

So, in theory the download is supposed to be cached, but it is not working https://github.com/goanpeca/setup-miniconda/blob/master/src/setup.ts#L204.

The caching you setup is for packages. (after miniconda has been installed)

**Comment by Borda** [comment]
> > I wanted to use some version lower than 4.8
> 
> Well why not trying to downgrade miniconda ? use the bundled one, but downgrade.

by "bundled" you mean default? by removing this version line?
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/workflows/pt-conda.yml#L55
mind advice what shall I change in the GH action config to get... :]

**Comment by goanpeca** [comment]
Yes. I have not tried it but it could work

so
```yaml
      with:
          # auto-update-conda: true
          auto-activate-base: false
          # miniconda-version: 4.7.12  # This downloads a new conda, use the conda-version
          conda-version: 4.7.12
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          activate-environment: pl-env
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
```

Maybe that is faster since it will NOT download a new miniconda, it will just downgrade conda.

**Comment by Borda** [comment]
Thx, just to verify, it seems that all the packages are downloaded, none is loaded from cache...
https://github.com/PyTorchLightning/pytorch-lightning/pull/2546/checks?check_run_id=847632269

**Comment by goanpeca** [comment]
>t seems that all the packages are downloaded, none is loaded from cache...

Bump the CACHE_VERSION by 1 and try again.

**Comment by Borda** [comment]
> Bump

that

**Comment by goanpeca** [comment]
@Borda you have PIP packages in https://github.com/PyTorchLightning/pytorch-lightning/blob/master/environment.yml#L40, to cache pip you need to add a separate cache option. https://github.com/actions/cache/blob/master/examples.md#python---pip

**Comment by Borda** [comment]
> > t seems that all the packages are downloaded, none is loaded from cache...
> 
> Bump the CACHE_VERSION by 1 and try again.

which shall create a new cache and the re-run to see if it was used correctly?

**Comment by goanpeca** [comment]
>which shall create a new cache and the re-run to see if it was used correctly?

Correct

**Comment by Borda** [comment]
> Borda you have PIP packages in https://github.com/PyTorchLightning/pytorch-lightning/blob/master/environment.yml#L40, to cache pip you need to add a separate cache option. https://github.com/actions/cache/blob/master/examples.md#python---pip

never tried, can I have multiple paths in one Cacheing step or just add another for pip?

**Comment by goanpeca** [comment]
Just add another one for pip

**Comment by Borda** [comment]
of after adding the extra cache but rather some other consequences lead to missing some libraries... I ques it is not connected to the condo setting, or am I missing init at every step beginning?

**Comment by Borda** [comment]
well we see this hanging for about an hour (it is cancelled by job timeout), see for example:
https://github.com/PyTorchLightning/metrics/pull/376/checks?check_run_id=3151677269

**Comment by bollwyvl** [comment]
Have you tried `miniforge-variant: Mambaforge`?

**Comment by Borda** [comment]
> Have you tried `miniforge-variant: Mambaforge`?

does it then use another cache?
https://github.com/PyTorchLightning/metrics/blob/dfc8f765cb6e2e512048327a401147ad8bec091a/.github/workflows/ci_test-conda.yml#L27-L32

**Comment by Borda** [comment]
ok, mamba does not work with caching from Readme... :/ any suggestion?

**Comment by jaimergp** [comment]
Hm, maybe `mamba` does not honor the `pkgs_dir` setting we are specifying in the config. I'll have a look.

Setup already takes <1min though, so not sure how much caching will actually improve timings here.

**Comment by Borda** [comment]
> Setup already takes <1min though, so not sure how much caching will actually improve timings here.

yes setup is fast, but the env update takes 8min to compare to running it with base conda which taes 3min
for the record: the env update in both cases contains the same packages, now testing in https://github.com/PyTorchLightning/metrics/pull/453

**Comment by jaimergp** [comment]
Ah sorry, didn't realize you were installing more stuff later.

**Comment by jaimergp** [comment]
Hm, wait, the last logs do show how `mamba` is hitting the cache: https://github.com/PyTorchLightning/metrics/runs/3348696215?check_suite_focus=true#step:7:462

**Comment by Borda** [comment]
Ok, I was checking some other log from the master which took 9min but could be because of an invalid cache...
I m no testing the `use-mamba: true` :rabbit:
