### ISSUE TITLE
Provide defaults example

### ISSUE THREAD

**Issue by henryiii** [conda-incubator/setup-miniconda#60]
GitHub Actions added a defaults feature that seems almost custom made for setup-miniconda; see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_iddefaultsrun

With that, you can set the default run shell to "bash -l {0}", for example, for all run steps. Using this in one of the examples in the readme would be helpful, I believe.

**Comment by goanpeca** [comment]
This is awesome @henryiii ! Thanks for sharing. I had asked for this in a couple of the github help forums. 

Glad to see it landed :-)
