### ISSUE TITLE
Is conda-forge added to channels by default?

### ISSUE THREAD

**Issue by ma-sadeghi** [conda-incubator/setup-miniconda#62]
I manually added `conda-forge` to channels, but I get the following warning:
```
Warning: 'conda-forge' already in 'channels' list, moving to the top
```

**Comment by goanpeca** [comment]
>Is conda-forge added to channels by default

No, but we update the configuration in 2 steps, the second time it happens, it may show something like this.

**Comment by ma-sadeghi** [comment]
Thanks for getting back to me. Is there a way to suppress the warning?

**Comment by goanpeca** [comment]
>Is there a way to suppress the warning?

Not currently, will look into for the next minor release.

**Comment by bilderbuchi** [comment]
I think this is a duplicate of #57.
