### ISSUE TITLE
New repo URL breaks existing workflows

### ISSUE THREAD

**Issue by jaimergp** [conda-incubator/setup-miniconda#70]
I would have expected runners to follow redirections for actions that have changed location, but they don't...

https://github.com/openforcefield/openforcefield/runs/1114396909?check_suite_focus=true

Thanks to @mattwthompson for the report!

**Comment by goanpeca** [comment]
Hi @jaimergp, yes I was expecting the redirects to last longer :-|

**Comment by mattwthompson** [comment]
It does seem to be working as expected after manually updating it: https://github.com/openforcefield/openforcefield/actions/runs/254560374

**Comment by goanpeca** [comment]
Thanks for the report @mattwthompson, leaving open as this will probably bite more people :-|

**Comment by jaimergp** [comment]
Are all users expected to manually migrate though? Maybe you can post the last version to your `goanpeca` namespace too, but adding a warning that it's changing locations and that the repo won't receive any more updates?

**Comment by goanpeca** [comment]
>Are all users expected to manually migrate though? Maybe you can post the last version to your goanpeca namespace too, but adding a warning that it's changing locations and that the repo won't receive any more updates?

Yep that would have been a better path 😆 

I do not have time to do this at the moment so I will just create a fork and add a warning later when time clears a bit.

Thanks for the suggestion.

**Comment by goanpeca** [comment]
Created this fork, so I guess this should bring it back to life ?

https://github.com/goanpeca/setup-miniconda

**Comment by jaimergp** [comment]
Thank you so much for the fast response! That will do in the meantime, yes!

**Comment by jaimergp** [comment]
I also raised this through their Twitter support and they are looking into it:

https://twitter.com/jaime_rgp/status/1305620040595763204

**Comment by jaimergp** [comment]
Twitter support has theoretically addressed this: https://twitter.com/mscccc/status/1306002367175823360

I don't know what we should do now, though:

a) Remove the fork and hope the redirection works
b) Keep the fork but add a deprecation warning pointing to the new URL

**Comment by goanpeca** [comment]
Let's go with b :-)

That would be the nice thing to do.

Now for how long would redirects work?

**Comment by jaimergp** [comment]
> I would favor b :-)

Agreed!

> Now for how long would redirects work?

As far as I know, they shouldn't expire? [source](https://twitter.com/mscccc/status/1308780155142156288)

**Comment by goanpeca** [comment]
Let's keep the fork for now while we add the new things.

**Comment by bollwyvl** [comment]
On account of #84, you'll probably want to upgrade to `v2` anyhow...

**Comment by goanpeca** [comment]
Just made release 2.2.0, and updated the fork as well. We should be safe now to close the fork and close this issue @jaimergp ?

**Comment by goanpeca** [comment]
I believe this is safe to close, updated release instructions to include an update to the fork and gave @jaimergp and @jezdez access to https://github.com/goanpeca/setup-miniconda just in case :)
