### ISSUE TITLE
Invitation to co-contribute and co-maintain

### ISSUE THREAD

**Issue by goanpeca** [conda-incubator/setup-miniconda#72]
Hello @bollwyvl, @bryanwweber, @jaimergp, @MGough, @marcelm, @jjhelmus, @HiromuHota and others I may have left out 😶 

As this action has gained more traction (it rhymes... you see what I did here? 🙃 ... 🤦) and moved to incubation I would like to invite some of you have been very active in the short life span of this project.

I would like to invite you to help co-contribute and co-maintain the project. 

If you would like to accept, this would involve:
- Getting commit rights 🥳 
- Making releases 📦 
- Helping other users 🆘 
- Review & merge PRs 🤓 
- Improve the action 📈 
- Maybe meet from time to time (like once per semester 🤷 ) to discuss whatever needs live discussion ☎️ 

Let me know what you think, also I could do a small onboarding meeting to go over some details so we can document it together.

Thanks a lot!

---

This is also an open invitation to users, in case you would like to get involved in an open source project. This is a small one and can help in providing a gentle introduction for newcomers to the OS world!

**Comment by jaimergp** [comment]
I'm in!

**Comment by goanpeca** [comment]
Created a new team, and added you @jaimergp. Thanks!

**Comment by bollwyvl** [comment]
Sure I'm your huckleberry. I have a clear and present need for the explicit
spec file PR, will revisit.

>

**Comment by goanpeca** [comment]
Added @bollwyvl :-p

**Comment by mattwthompson** [comment]
I'd be happy to help to the limited extent I can, since we now depend on it to a significant extent and it's a great tool. Watching the repo now in case I can chime in or contribute 🙂

**Comment by goanpeca** [comment]
Added @mattwthompson if you have questions, just ask :-)

**Comment by HiromuHota** [comment]
@goanpeca thanks for the invite. I'm happy to contribute!

**Comment by goanpeca** [comment]
Added @HiromuHota

**Comment by goanpeca** [comment]
Thanks for everyone who volunteered to help and of course to all our users.

Closing!
