### ISSUE TITLE
2.0 release plans

### ISSUE THREAD

**Issue by bollwyvl** [conda-incubator/setup-miniconda#83]
We have merged a number of changes since 1.7. Let's figure out what [we](https://github.com/conda-incubator/setup-miniconda/issues/72) need to do to get a new release out!

Looking over the docs, here's my stab at it:

- [x] bump versions (#83)
- [ ] docs 
  - [ ] better example links (pick one)
    - [ ] #82 
    - [ ] #86
  - [x] add changelog (#85)
- [ ] make new tag
  - [ ] make/move :scream:  convenience tag 
- [ ] update release process with lessons learned
- [ ] blog post?

**Comment by bollwyvl** [comment]
Looking over the release docs... I really don't know if i like changing tags after the fact... but i guess if that's what people expect...

**Comment by goanpeca** [comment]
Hi @bollwyvl 

Thanks for raising this issue!

I am out for holidays so feel free to start :-)

Regarding the tag change I think I read somewhere on GitHub docs that it was the recommended.

Maybe changes deserve a 2.x ?

**Comment by bollwyvl** [comment]
Enjoy :surfer: :skier: or whatever it is you're up to!

I'll start a CHANGELOG PR, and we can determine whether there's enough meat for a full bump...

**Comment by bollwyvl** [comment]
Yeah, would be great to get this out.

A 2.0 seems fine! Let me know and I can add that to #85...

**Comment by bollwyvl** [comment]
K, everything looking :green_heart: on master... really just need to pick which of the README badge treatments we want... I'll defer that choice (or deferring to another day) and the actual tagging to @goanpeca !

**Comment by goanpeca** [comment]
Ok @bollwyvl doing the tag today :)

**Comment by bollwyvl** [comment]
Awesome. I'm afk, but let me know if I can help with... Something?

**Comment by bollwyvl** [comment]
@goanpeca back at keyboard, but getting :sleepy: ... anything I can do to hep?

**Comment by bollwyvl** [comment]
kicking the tires on 16930e6 [over here](https://github.com/krassowski/jupyterlab-lsp/pull/401)... nothing to report yet...

**Comment by bollwyvl** [comment]
Looks solid over there!

**Comment by goanpeca** [comment]
Thanks @bollwyvl !
