### ISSUE TITLE
Silent errors with faulty environment file

### ISSUE THREAD

**Issue by jaimergp** [conda-incubator/setup-miniconda#93]
If a user provides an invalid YAML file (e.g. wrong section name), the action fails to update the environment with that file, but doesn't report the failure.

To reproduce, try using a YAML file like this:

```
name: test
channels:
  - conda-forge
  - defaults
requirements:
  - compilers
  - python
```

Note how I used `requirements` instead of `dependencies`. You will see this unreported error:

```
# Updating conda environment from yaml file...
##############################################

/usr/share/miniconda/condabin/conda env update --file devtools/conda-envs/test_env.yaml --name test

EnvironmentSectionNotValid: The following section on '/home/runner/work/yank/yank/devtools/conda-envs/test_env.yaml' is invalid and will be ignored:
 - requirements

#
# To activate this environment, use
#
#     $ conda activate test
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```

[Example on a real log](https://github.com/choderalab/yank/pull/1244/checks?check_run_id=1399580088#step:4:782).

**Comment by goanpeca** [comment]
Hi @jaimergp thanks for the report!

Could you try to debug this by adding some `console.log`here with https://github.com/conda-incubator/setup-miniconda/blob/master/src/setup.ts#L113 ?

It might be that `conda env` is not actually raising the right exit codes and we might need to add some extra logic to check for the output text.

**Comment by jaimergp** [comment]
Yes, you are right, `conda env` does not return `1` because that invalid section is simply ignored. I guess we'll have to inspect `stdout` for `EnvironmentSectionNotValid`.

**Comment by goanpeca** [comment]
>I guess we'll have to inspect stdout for EnvironmentSectionNotValid.

Yes, exactly. Thanks for confirming this :) 

Wanna take a stab at it?

**Comment by jaimergp** [comment]
I am not familiar with JS/TS at all, but I'll try! The string should be available [here](https://github.com/conda-incubator/setup-miniconda/blob/master/src/setup.ts#L110), right?

**Comment by goanpeca** [comment]
You may need to add listener for the stdout (if those errors are not printed to sterr, but to stdout)
