### ISSUE TITLE
installer-url option triggers an error on windows

### ISSUE THREAD

**Issue by rvianello** [conda-incubator/setup-miniconda#97]
I'm trying to use the miniforge distribution, it works just as expected for linux and osx, but on windows it fails when trying to cache the downloaded installer, and it logs the following output:

```
# 
# Downloading Custom Installer...

#####################################

Miniforge3-Windows-x86_64.exe
Saving cache...
Error: EINVAL: invalid argument, mkdir 'C:\hostedtoolcache\windows\https:\github.com\conda-forge\miniforge\releases\latest\download\Miniforge3-Windows-x86_64.exe\https:\github.com\conda-forge\miniforge\releases\latest\download\Miniforge3-Windows-x86_64.exe\x64'
```

I suspect the error could be due to the additional `:` characters in the directory path, coming from the url schema?

Thanks a lot for developing this action,

Best,
Riccardo

**Comment by bollwyvl** [comment]
Wow didn't know there was a MF for windows! Thanks for the report!

We need to add that to CI, for sure!

**Comment by rvianello** [comment]
Thanks a lot for the very quick fix!

**Comment by bollwyvl** [comment]
Thanks for bringing it to our attention... I feel there's a bit of a sea change coming, and we'll be seeing more custom installers in the future.... :monorail:
