### ISSUE TITLE
Usage of set-env causes failures if ACTIONS_ALLOW_UNSECURE_COMMANDS is not defined

### ISSUE THREAD

**Issue by andfoy** [conda-incubator/setup-miniconda#99]
This is the traceback from the GitHub actions CI. It seems that the usage of `set-env` was disabled in order to fix some security concerns.

```
Error: Unable to process command '::set-env name=RUN_BUILD::true' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by jaimergp** [comment]
Upgrade to `v2`!

**Comment by andfoy** [comment]
@jaimergp, thanks for the quick response, I'll close this one then

**Comment by jaimergp** [comment]
Thank _you_ for raising the issue! We knew this was coming but we didn't know how the actual error was going to look like, so now users that are late to the upgrade party will be able to find this when they look it up! 🎉
